//////////////////////////////////////////////////////////////////////////
//
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//
//////////////////////////////////////////////////////////////////////////

#ifndef UNITY_TERRAIN_TOOL_NOISE_NoneBillow_INC
#define UNITY_TERRAIN_TOOL_NOISE_NoneBillow_INC

/*=========================================================================

    Includes

=========================================================================*/

#include "../Implementation/BillowImpl.hlsl"
#include "../NoiseCommon.hlsl"



/*=========================================================================
    
    NoneBillow Noise Functions - Non-Fractal, Non-Warped

=========================================================================*/

float noise_NoneBillow( float pos )
{
    return get_noise_Billow( pos );
}

float noise_NoneBillow( float2 pos )
{
    return get_noise_Billow( pos );
}

float noise_NoneBillow( float3 pos )
{
    return get_noise_Billow( pos );
}

float noise_NoneBillow( float4 pos )
{
    return get_noise_Billow( pos );
}

#endif // UNITY_TERRAIN_TOOL_NOISE_NoneBillow_INC