//////////////////////////////////////////////////////////////////////////
//
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//      DO NOT EDIT THIS FILE!! THIS IS AUTOMATICALLY GENERATED!!
//
//////////////////////////////////////////////////////////////////////////

#ifndef UNITY_TERRAIN_TOOL_NOISE_NonePerlin_INC
#define UNITY_TERRAIN_TOOL_NOISE_NonePerlin_INC

/*=========================================================================

    Includes

=========================================================================*/

#include "../Implementation/PerlinImpl.hlsl"
#include "../NoiseCommon.hlsl"



/*=========================================================================
    
    NonePerlin Noise Functions - Non-Fractal, Non-Warped

=========================================================================*/

float noise_NonePerlin( float pos )
{
    return get_noise_Perlin( pos );
}

float noise_NonePerlin( float2 pos )
{
    return get_noise_Perlin( pos );
}

float noise_NonePerlin( float3 pos )
{
    return get_noise_Perlin( pos );
}

float noise_NonePerlin( float4 pos )
{
    return get_noise_Perlin( pos );
}

#endif // UNITY_TERRAIN_TOOL_NOISE_NonePerlin_INC